{{- if $.Values.cluster.certManagerEnabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterIssuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.cluster.letsEncryptAccountEmail }}
    privateKeySecretRef:
      name: letsencrypt-clusterIssuer-secret
    solvers:
    - http01:
        ingress:
  {{- if $.Values.cluster.isGKE }}
          name: gce
  {{- else }}
          name: nginx
  {{- end }}
{{- end }}
